name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
    - master
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t "${PWD##*/}" .
      - run: docker run "${PWD##*/}" python -V
      - run: docker run "${PWD##*/}" codeql --version
